- name: Install kubernetes.repo
  copy:
    src: kubernetes.repo
    dest: /etc/yum.repos.d/

- name: Install kubelet, kubeadm, kubectl
  yum:
    name: "{{ packages }}"
    disable_excludes: kubernetes
  vars:
    packages:
      - kubelet
      - kubeadm
      - kubectl

- name: Enable kubelet
  service:
    name: kubelet
    enabled: yes
    state: started

- name: Install sysctl.d/k8s.conf
  copy:
    src: sysctl.k8s.conf
    dest: /etc/sysctl.d/k8s.conf

- name: Reload sysctl
  command: sysctl --system
